---
sidebar: sidebar 
permalink: concept-privacy.html 
keywords: privacy, data privacy, credentials, access to credentials, hashicorp vault 
summary: 'NetApp non ha accesso alle credenziali fornite durante l"utilizzo del servizio di copia e sincronizzazione BlueXP. Le credenziali vengono memorizzate direttamente sulla macchina del data broker, che risiede nella rete.' 
---
= Privacy dei dati
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp non ha accesso alle credenziali fornite durante l'utilizzo del servizio di copia e sincronizzazione BlueXP. Le credenziali vengono memorizzate direttamente sulla macchina del data broker, che risiede nella rete.

A seconda della configurazione scelta, la copia e la sincronizzazione di BlueXP potrebbero richiedere le credenziali quando si crea una nuova relazione. Ad esempio, quando si imposta una relazione che include un server SMB o quando si implementa il data broker in AWS.

Queste credenziali vengono sempre salvate direttamente nel data broker stesso. Il data broker risiede su un computer della tua rete, sia esso on-premise che nel tuo account cloud. Le credenziali non vengono mai rese disponibili a NetApp.

Le credenziali vengono crittografate localmente sulla macchina del broker di dati utilizzando HashiCorp Vault.
