---
sidebar: sidebar 
permalink: task-licensing.html 
keywords: license, subscription, registering, subscribing, subscribing in aws, subscribing in azure, subscribing to aws, subscribing to azure, aws marketplace, azure marketplace, netapp license, byol license, purchase a license, license settings, pay for relationships, paygo, annual, pay-as-you-go 
summary: 'Esistono due modi per pagare le relazioni di sincronizzazione dopo la fine della prova gratuita di 14 giorni. La prima opzione consiste nel pagare a consumo. La seconda opzione consiste nell"acquistare le licenze direttamente da NetApp.' 
---
= Pagamento delle relazioni di sincronizzazione al termine della prova gratuita
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Esistono due modi per pagare le relazioni di sincronizzazione dopo la fine della prova gratuita di 14 giorni. La prima opzione consiste nell'abbonarsi ad AWS o Azure per il pagamento a consumo o per il pagamento annuale. La seconda opzione consiste nell'acquistare le licenze direttamente da NetApp.

Puoi iscriverti da AWS Marketplace o Azure Marketplace. Non puoi iscriverti a entrambi.

È possibile utilizzare le licenze di NetApp con un abbonamento a Marketplace. Ad esempio, se si dispone di 25 relazioni di sincronizzazione, è possibile pagare le prime 20 relazioni di sincronizzazione utilizzando una licenza e quindi pagare a consumo da AWS o Azure con le restanti 5 relazioni di sincronizzazione.

link:concept-licensing.html["Scopri di più sul funzionamento delle licenze"].

Se non pagherai subito dopo la fine della prova gratuita, non potrai creare ulteriori relazioni. Le relazioni esistenti non vengono eliminate, ma non è possibile apportare modifiche fino a quando non si sottoscrive o si inserisce una licenza.

Le licenze devono essere gestite tramite BlueXP Copy and Sync o il sito Web applicabile e *non* tramite un portafoglio digitale.



== [[aws]]sottoscrizione da AWS

AWS ti consente di pagare a consumo o di pagare annualmente.

.Procedura per il pagamento a consumo
. Fare clic su *Sync > Licensing*.
. Selezionare *AWS*
. Fare clic su *Iscriviti*, quindi su *continua*.
. Iscriviti a AWS Marketplace, quindi accedi nuovamente al servizio di copia e sincronizzazione BlueXP per completare la registrazione.
+
Il seguente video mostra il processo:

+
video::video_cloud_sync_registering.mp4[width=848,height=480]


.Passi da pagare annualmente
. https://aws.amazon.com/marketplace/pp/B06XX5V3M2["Accedere alla pagina AWS Marketplace"^].
. Fare clic su *continua per iscriversi*.
. Selezionare le opzioni del contratto e fare clic su *Crea contratto*.




== [[Azure]]sottoscrizione a Azure

Azure ti consente di pagare in base alle tue esigenze o di pagare ogni anno.

.Di cosa hai bisogno
Un account utente Azure che dispone delle autorizzazioni Contributor o Owner nell'abbonamento pertinente.

.Fasi
. Fare clic su *Sync > Licensing*.
. Selezionare *Azure*.
. Fare clic su *Iscriviti*, quindi su *continua*.
. Nel portale Azure, fare clic su *Create*, selezionare le opzioni e fare clic su *Subscribe*.
+
Seleziona *mensile* per pagare in base all'ora o *annuale* per pagare in anticipo un anno.

. Una volta completata l'implementazione, fare clic sul nome della risorsa SaaS nella finestra a comparsa di notifica.
. Fare clic su *Configure account* (Configura account) per tornare alla copia e alla sincronizzazione di BlueXP.
+
Il seguente video mostra il processo:

+
video::video_cloud_sync_registering_azure.mp4[width=848,height=480]




== [[licenses]]Acquisto di licenze NetApp e aggiunta a BlueXP copy e Sync

Per pagare anticipatamente le relazioni di sincronizzazione, è necessario acquistare una o più licenze e aggiungerle al servizio di copia e sincronizzazione BlueXP.

.Di cosa hai bisogno
Sono necessari il numero di serie della licenza e il nome utente e la password per l'account NetApp Support Site a cui è associata la licenza.

.Fasi
. Acquista una licenza inviando un messaggio di posta:ng-cloudsync-contact@netapp.com?subject=Cloud%20Sync%20Service%20-%20BYOL%20License%20Purchase%20Request[come contattare NetApp].
. In BlueXP, fare clic su *Sync > Licensing*.
. Fare clic su *Add License* (Aggiungi licenza) e aggiungere le informazioni richieste:
+
.. Inserire il numero di serie.
.. Selezionare l'account NetApp Support Site associato alla licenza che si desidera aggiungere:
+
*** Se l'account è già stato aggiunto a BlueXP, selezionarlo dall'elenco a discesa.
*** Se l'account non è stato ancora aggiunto, fare clic su *Aggiungi credenziali NSS*, immettere il nome utente e la password, fare clic su *Registra*, quindi selezionarlo dall'elenco a discesa.


.. Fare clic su *Aggiungi*.






== Aggiornamento di una licenza

Se hai esteso una licenza di copia e sincronizzazione BlueXP acquistata da NetApp, la nuova data di scadenza non verrà aggiornata automaticamente in BlueXP Copy and Sync. È necessario aggiungere nuovamente la licenza per aggiornare la data di scadenza. Le licenze devono essere gestite tramite BlueXP Copy and Sync o il sito Web applicabile e *non* tramite un portafoglio digitale.

.Fasi
. In BlueXP, fare clic su *Sync > Licensing*.
. Fare clic su *Add License* (Aggiungi licenza) e aggiungere le informazioni richieste:
+
.. Inserire il numero di serie.
.. Selezionare l'account NetApp Support Site associato alla licenza che si desidera aggiungere.
.. Fare clic su *Aggiungi*.




.Risultato
BlueXP Copy and Sync aggiorna la licenza esistente con la nuova data di scadenza.
