---
sidebar: sidebar 
permalink: task-licensing.html 
keywords: license, subscription, registering, subscribing, subscribing in aws, subscribing in azure, subscribing to aws, subscribing to azure, aws marketplace, azure marketplace, netapp license, byol license, purchase a license, license settings, pay for relationships, paygo, annual, pay-as-you-go 
summary: 'Esistono due modi per pagare le relazioni di sincronizzazione dopo la fine della prova gratuita di 14 giorni. La prima opzione consiste nel pagare a consumo. La seconda opzione consiste nell"acquistare le licenze direttamente da NetApp.' 
---
= Paga le relazioni di sincronizzazione al termine della prova gratuita
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Esistono due modi per pagare le relazioni di sincronizzazione dopo la fine della prova gratuita di 14 giorni. La prima opzione consiste nell'abbonarsi ad AWS o Azure per il pagamento a consumo o per il pagamento annuale. La seconda opzione consiste nell'acquistare le licenze direttamente da NetApp.

Puoi iscriverti da AWS Marketplace o Azure Marketplace. Non puoi iscriverti a entrambi.

È possibile utilizzare le licenze di NetApp con un abbonamento a Marketplace. Ad esempio, se si dispone di 25 relazioni di sincronizzazione, è possibile pagare le prime 20 relazioni di sincronizzazione utilizzando una licenza e quindi pagare a consumo da AWS o Azure con le restanti 5 relazioni di sincronizzazione.

link:concept-licensing.html["Scopri di più sul funzionamento delle licenze"].

Se non pagherai subito dopo la fine della prova gratuita, non potrai creare ulteriori relazioni. Le relazioni esistenti non vengono eliminate, ma non è possibile apportare modifiche fino a quando non si sottoscrive o si inserisce una licenza.

Le licenze devono essere gestite tramite BlueXP Copy and Sync o il sito Web applicabile e *non* tramite un portafoglio digitale.



== [[aws]]effettua l'iscrizione ad AWS

AWS ti consente di pagare a consumo o di pagare annualmente.

.Procedura per il pagamento a consumo
. Dal menu di navigazione di BlueXP , selezionare *mobilità > Copia e sincronizza*.
. Selezionare *licenze*.
. Selezionare *AWS*.
. Selezionare *Subscribe*, quindi selezionare *Continue* (continua).
. Iscriviti a AWS Marketplace, quindi accedi nuovamente al servizio di copia e sincronizzazione BlueXP per completare la registrazione.
+
Il seguente video mostra il processo:

+
.Iscriviti alla copia BlueXP  e sincronizzarla da AWS Marketplace
video::796ffd6d-cade-4750-8504-b24c010b225d[panopto]


.Passi da pagare annualmente
. https://aws.amazon.com/marketplace/pp/B06XX5V3M2["Accedere alla pagina AWS Marketplace"^].
. Selezionare *continua per iscriversi*.
. Selezionare le opzioni del contratto, quindi selezionare *Crea contratto*.




== [[Azure]]Iscriviti da Azure

Azure ti consente di pagare in base alle tue esigenze o di pagare ogni anno.

.Di cosa hai bisogno
Un account utente Azure che dispone delle autorizzazioni Contributor o Owner nell'abbonamento pertinente.

.Fasi
. Dal menu di navigazione di BlueXP , selezionare *mobilità > Copia e sincronizza*.
. Selezionare *licenze*.
. Selezionare *Azure*.
. Selezionare *Subscribe*, quindi selezionare *Continue* (continua).
. Nel portale Azure, selezionare *Crea*, selezionare le opzioni desiderate, quindi selezionare *Iscriviti*.
+
Seleziona *mensile* per pagare in base all'ora o *annuale* per pagare in anticipo un anno.

. Una volta completata l'implementazione, selezionare il nome della risorsa SaaS nella finestra a comparsa di notifica.
. Selezionare *Configure account* (Configura account) per tornare alla copia e alla sincronizzazione di BlueXP.
+
Il seguente video mostra il processo:

+
.Iscriviti alla copia BlueXP  e sincronizzala da Azure Marketplace
video::a6a39447-b7b1-42f6-9c89-b24c010b21b9[panopto]




== [[licenses]]acquistare licenze da NetApp e aggiungerle alla copia e alla sincronizzazione di BlueXP 

Per pagare anticipatamente le relazioni di sincronizzazione, è necessario acquistare una o più licenze e aggiungerle al servizio di copia e sincronizzazione BlueXP.

.Di cosa hai bisogno
Sono necessari il numero di serie della licenza e il nome utente e la password per l'account NetApp Support Site a cui è associata la licenza.

.Fasi
. Acquista una licenza inviando un messaggio di posta:ng-cloudsync-contact@netapp.com?subject=Cloud%20Sync%20Service%20-%20BYOL%20License%20Purchase%20Request[come contattare NetApp].
. Dal menu di navigazione di BlueXP , selezionare *mobilità > Copia e sincronizza*.
. Selezionare *licenze*.
. Selezionare *Add License* (Aggiungi licenza) e aggiungere le informazioni richieste:
+
.. Inserire il numero di serie.
.. Selezionare l'account NetApp Support Site associato alla licenza che si desidera aggiungere:
+
*** Se l'account è già stato aggiunto a BlueXP, selezionarlo dall'elenco a discesa.
*** Se l'account non è stato ancora aggiunto, selezionare *Aggiungi credenziali NSS*, immettere il nome utente e la password, selezionare *Registra*, quindi selezionarlo dall'elenco a discesa.


.. Selezionare *Aggiungi*.






== Aggiornare una licenza

Se hai esteso una licenza di copia e sincronizzazione BlueXP acquistata da NetApp, la nuova data di scadenza non verrà aggiornata automaticamente in BlueXP Copy and Sync. È necessario aggiungere nuovamente la licenza per aggiornare la data di scadenza. Le licenze devono essere gestite tramite BlueXP Copy and Sync o il sito Web applicabile e *non* tramite un portafoglio digitale.

.Fasi
. Dal menu di navigazione di BlueXP , selezionare *mobilità > Copia e sincronizza*.
. Selezionare *licenze*.
. Selezionare *Add License* (Aggiungi licenza) e aggiungere le informazioni richieste:
+
.. Inserire il numero di serie.
.. Selezionare l'account NetApp Support Site associato alla licenza che si desidera aggiungere.
.. Selezionare *Aggiungi*.




.Risultato
BlueXP Copy and Sync aggiorna la licenza esistente con la nuova data di scadenza.
